include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/generated/**
    
linter:
  rules:
    sort_pub_dependencies: false
    always_use_package_imports: true
