name: reversi_battle
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Localizations
  flutter_localizations:
    sdk: flutter

  # State management
  hooks_riverpod: ^1.0.4
  flutter_hooks: ^0.18.5+1

  # Code generator
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  flutter_gen: ^4.3.0

  # Others
  flutter_svg: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter
  flutter_lints: ^2.0.0

  # Code generator
  freezed: ^2.1.0+1
  build_runner: ^2.2.0
  flutter_gen_runner: ^4.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true
  class_name: L
  main_locale: ja
  arb_dir: assets/l10n
  output_dir: lib/generated
