import 'package:flutter/material.dart';
import 'package:reversi_battle/utils/res/res.dart';

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: kPrimary,
  onPrimary: kOnPrimary,
  primaryContainer: kPrimaryContainer,
  onPrimaryContainer: kOnPrimaryContainer,
  secondary: kSecondary,
  onSecondary: kOnSecondary,
  secondaryContainer: kSecondaryContainer,
  onSecondaryContainer: kOnSecondaryContainer,
  tertiary: kTertiary,
  onTertiary: kOnTertiary,
  tertiaryContainer: kTertiaryContainer,
  onTertiaryContainer: kOnTertiaryContainer,
  error: kError,
  onError: kOnError,
  errorContainer: kErrorContainer,
  onErrorContainer: kOnErrorContainer,
  background: kBackground,
  onBackground: kOnBackground,
  surface: kSurface,
  onSurface: kOnSurface,
  surfaceVariant: kSurfaceVariant,
  onSurfaceVariant: kOnSurfaceVariant,
  outline: kOutline,
  inverseSurface: kInverseSurface,
  onInverseSurface: kOnInverseSurface,
  inversePrimary: kInversePrimary,
  shadow: kShadow,
);

const darkColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: kPrimary,
  onPrimary: kOnPrimary,
  primaryContainer: kPrimaryContainer,
  onPrimaryContainer: kOnPrimaryContainer,
  secondary: kSecondary,
  onSecondary: kOnSecondary,
  secondaryContainer: kSecondaryContainer,
  onSecondaryContainer: kOnSecondaryContainer,
  tertiary: kTertiary,
  onTertiary: kOnTertiary,
  tertiaryContainer: kTertiaryContainer,
  onTertiaryContainer: kOnTertiaryContainer,
  error: kError,
  onError: kOnError,
  errorContainer: kErrorContainer,
  onErrorContainer: kOnErrorContainer,
  background: kBackground,
  onBackground: kOnBackground,
  surface: kSurface,
  onSurface: kOnSurface,
  surfaceVariant: kSurfaceVariant,
  onSurfaceVariant: kOnSurfaceVariant,
  outline: kOutline,
  inverseSurface: kInverseSurface,
  onInverseSurface: kOnInverseSurface,
  inversePrimary: kInversePrimary,
  shadow: kShadow,
);
